name: Release

on:
  push:
    tags:
      - 'v*' # Trigger on version tags

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        deno-version: ['2.x', '22.x']
        include:
          - os: ubuntu-latest
            deno-version: '2.x'
            artifact_name: lesspaper-linux-deno2
          - os: ubuntu-latest
            deno-version: '22.x'
            artifact_name: lesspaper-linux-deno22
          - os: macos-latest
            deno-version: '2.x'
            artifact_name: lesspaper-macos-deno2
          - os: macos-latest
            deno-version: '22.x'
            artifact_name: lesspaper-macos-deno22

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: Install UI Dependencies
        working-directory: ui
        run: npm install

      - name: Install System Dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install imagemagick tesseract

      - name: Install System Dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick tesseract-ocr

      - name: Build and Compile
        run: deno task compile

      - name: Rename Binary
        run: |
          mv build/lesspaper build/${{ matrix.artifact_name }}

      - name: Upload Binary as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: build/${{ matrix.artifact_name }}

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: build/${{ matrix.artifact_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
